[build.environment]

[context.production.branch-deploy]
    command = "mv robots-disallow.txt robots.txt"


[context.production]
    command = "mv robots-production.txt robots.txt"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200